server:
  port: 8080
spring:
  application:
    name: zagame # 当前服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zagame
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 服务注册地址（Nacos地址
    datasource:
      url: jdbc:mysql://localhost:3306/zagame
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3
      # password:
      pool:
        minIdle: 1
        maxIdle: 10
        maxWait: 3
        maxActive: 8

